[web]
web01 ansible_host=10.10.10.11
web02 ansible_host=10.10.10.14

[was]
was01 ansible_host=10.10.10.12
was02 ansible_host=10.10.10.15

[db]
db01 ansible_host=10.10.10.13

[all:vars]
ansible_user=kbs
ansible_become=yes
